DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS country;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE country (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    capital TEXT UNIQUE NOT NULL,
    population INTEGER NOT NULL
);
